version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vosiz_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./public/storage:/var/www/html/public/storage
    depends_on:
      - mysql
      - mongodb
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - vosiz_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: vosiz_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vosiz_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: vosiz_user
      MYSQL_PASSWORD: vosiz_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - vosiz_network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: vosiz_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: vosiz_mongo
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    ports:
      - "27018:27017"
    networks:
      - vosiz_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7.2-alpine
    container_name: vosiz_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - vosiz_network

  # phpMyAdmin (Optional - for MySQL management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vosiz_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: vosiz_user
      PMA_PASSWORD: vosiz_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - vosiz_network

  # Mongo Express (Optional - for MongoDB management)
  mongo-express:
    image: mongo-express
    container_name: vosiz_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - vosiz_network

# Networks
networks:
  vosiz_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local